# DealFinder Domain Models
from src.domain.models import (
    User,
    DealFilter,
    Deal,
    DealSnapshot,
    DealReport,
    DealClick,
    ReportOpen,
    KeepaApiLog,
    PriceRange,
    DiscountRange,
    EmailSchedule,
    FilterConfig,
    CreateFilterRequest,
    DealSearchQuery,
    DealSearchResult,
    SearchResponse,
    ClickTrackingRequest,
    ClickTrackingResponse,
)

__all__ = [
    "User",
    "DealFilter",
    "Deal",
    "DealSnapshot",
    "DealReport",
    "DealClick",
    "ReportOpen",
    "KeepaApiLog",
    "PriceRange",
    "DiscountRange",
    "EmailSchedule",
    "FilterConfig",
    "CreateFilterRequest",
    "DealSearchQuery",
    "DealSearchResult",
    "SearchResponse",
    "ClickTrackingRequest",
    "ClickTrackingResponse",
]
